-- do not edit; automatically generated by UU.AG
module Top.Cobalt.AGSyntax where
-- AGAttr ------------------------------------------------------
data AGAttr = AGAttr (String) (Attr) (String) (String)
-- AGAttrs -----------------------------------------------------
type AGAttrs = [(AGAttr)]
-- AGCode ------------------------------------------------------
data AGCode = AGCode (AGDatas) (AGAttrs) (AGSems)
-- AGData ------------------------------------------------------
data AGData = AGData (String) (String) ([(String, String)])
-- AGDatas -----------------------------------------------------
type AGDatas = [(AGData)]
-- AGSem -------------------------------------------------------
data AGSem = AGSem (String) (String) (AGSemDecls)
-- AGSemDecl ---------------------------------------------------
data AGSemDecl = AGSemDecl (String) (String) (String)
-- AGSemDecls --------------------------------------------------
type AGSemDecls = [(AGSemDecl)]
-- AGSems ------------------------------------------------------
type AGSems = [(AGSem)]
-- Attr --------------------------------------------------------
data Attr = Chained 
          | Inherited 
          | Synthesized 


