-- do not edit; automatically generated by UU.AG
module Top.Cobalt.Syntax where

import Top.Cobalt.AGSyntax
import Top.Cobalt.ShowAG
-- ConstraintTerm ----------------------------------------------
data ConstraintTerm = ConstraintTerm (Term)
-- ConstraintTerms ---------------------------------------------
type ConstraintTerms = [(ConstraintTerm)]
-- DeductionRule -----------------------------------------------
data DeductionRule = DeductionRule (Judgements) (Judgement)
-- Judgement ---------------------------------------------------
data Judgement = Judgement (Terms) (Term) (Terms)
-- JudgementDecl -----------------------------------------------
data JudgementDecl = JudgementDecl (String) ([String]) ([String])
-- JudgementDecls ----------------------------------------------
type JudgementDecls = [(JudgementDecl)]
-- Judgements --------------------------------------------------
type Judgements = [(Judgement)]
-- Term --------------------------------------------------------
data Term = TermApp (String) (Terms)
          | TermString (String)
          | TermVar (String)
-- Terms -------------------------------------------------------
type Terms = [(Term)]
-- TypeRule ----------------------------------------------------
data TypeRule = TypeRule (String) (DeductionRule) (ConstraintTerms)
-- TypeRules ---------------------------------------------------
type TypeRules = [(TypeRule)]
-- TypeSystem --------------------------------------------------
data TypeSystem = TypeSystem (AGDatas) (JudgementDecls) (TypeRules)


